---
- name: Install and Configure Docker
  hosts: webservers
  remote_user: ansible
  connection: ssh
  become: yes

  tasks:
  - name: Install Docker
    yum:
      name: docker
      state: present

  - name: Install python-pip
    yum:
      name: python-pip
      state: present

  - name: Install docker-py
    pip:
      name: docker-py
      state: present

  - name: Start and Enable Docker
    service:
      name: docker
      state: started
      enabled: yes

  - name: Disable SELinux
    selinux:
      state: disabled

  - name: Pull Docker image
    docker_image:
      name: nginx
      source: pull

  - name: Run Docker container
    docker_container:
      name: my_nginx
      image: nginx
      state: started
      ports:
        - "8081:80"

  handlers:
  - name: Restart Docker
    service:
      name: docker
      state: restarted
