---
- hosts: webservers
  remote_user: ansible
  become: yes
  connection: ssh

  tasks:
  - name: Install HTTPD server on centos 7
    yum:
      name: httpd
      state: present
    notify: restart HTTPD

  handlers:
  - name: restart HTTPD
    service:
      name: httpd
      state: restarted
