---
- name: Install and Configure httpd Server
  hosts: webservers
  remote_user: ansible
  connection: ssh
  become: yes

  vars:
    httpd_port: 8080
    server_name: "example.com"

  tasks:
  - name: Install httpd
    yum:
      name: httpd
      state: present

  - name: Start and Enable httpd
    service:
      name: httpd
      state: started
      enabled: yes

  - name: Configure httpd
    template:
      src: templates/httpd.conf.j2
      dest: /etc/httpd/conf/httpd.conf
    notify: Restart httpd

  - name: Check httpd service status
    command: systemctl status httpd.service
    ignore_errors: yes
    register: httpd_status

  - name: Print httpd service status
    debug:
      msg: "{{ httpd_status.stdout }}"

  handlers:
  - name: Restart httpd
    service:
      name: httpd
      state: restarted
