---
- name: Install and Configure httpd Server
  hosts: webservers
  remote_user: ansible
  connection: ssh
  become: yes

  vars:
    httpd_port: 8080
    server_name: "example.com"

  tasks:
  - name: Install httpd and dependencies
    yum:
      name:
        - httpd
        - libselinux-python
      state: present

  - name: Disable SELinux
    selinux:
      state: disabled

  - name: Install firewalld
    yum:
      name:
        - firewalld
        - python-firewall
      state: present

  - name: Start and Enable firewalld
    service:
      name: firewalld
      state: started
      enabled: yes

  - name: Configure httpd
    template:
      src: templates/httpd.conf.j2
      dest: /etc/httpd/conf/httpd.conf
    notify: Restart httpd

  - name: Allow httpd port in firewall
    firewalld:
      port: "{{ httpd_port }}/tcp"
      permanent: yes
      state: enabled

  - name: Reload firewalld
    service:
      name: firewalld
      state: reloaded

  - name: Start and Enable httpd
    service:
      name: httpd
      state: started
      enabled: yes

  handlers:
  - name: Restart httpd
    service:
      name: httpd
      state: restarted
