---
- name: Install and Configure Docker
  hosts: webservers
  remote_user: ansible
  connection: ssh
  become: yes

  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
  - name: Install Docker and dependencies
    yum:
      name:
        - docker
        - python3-docker
      state: present

  - name: Start and Enable Docker
    service:
      name: docker
      state: started
      enabled: yes

  - name: Pull Docker image
    docker_image:
      name: nginx
      source: pull

  - name: Run Docker container
    docker_container:
      name: my_nginx
      image: nginx
      state: started
      ports:
        - "8080:80"

  handlers:
  - name: Restart Docker
    service:
      name: docker
      state: restarted
