---
- name: Install Git, Python, and Java if not installed
  hosts: webserver
  user: ansible
  connection: ssh
  become: yes
  tasks:
    - name: Check if Git is installed
      ansible.builtin.shell: which git
      register: git_check
      ignore_errors: yes

    - name: Install Git if not installed
      ansible.builtin.package:
        name: git
        state: present
      when: git_check.rc != 0

    - name: Check if Python is installed
      ansible.builtin.shell: which python3
      register: python_check
      ignore_errors: yes

    - name: Install Python if not installed
      ansible.builtin.package:
        name: python3
        state: present
      when: python_check.rc != 0

    - name: Check if Java is installed
      ansible.builtin.shell: java -version
      register: java_check
      ignore_errors: yes

    - name: Install Java if not installed
      ansible.builtin.package:
        name: java-1.8.0-openjdk
        state: present
      when: java_check.rc != 0
